### ISSUE TITLE
Directory structure is not correct

### ISSUE THREAD

**Issue by kelloggm** [Kevin-TD/c-resource-leak-checker#2]
When building in the docker container, following the README's instructions leads to an error:
> CMake Error: The current CMakeCache.txt directory /C-resource-leak-checker/build/CMakeCache.txt is different than the directory /resource leak checker/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
> CMake Error: The source "/C-resource-leak-checker/CMakeLists.txt" does not match the source "/resource leak checker/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.

Creating a new directory called "resource leak checker" and re-trying succeeds, but the instructions and/or dockerfile need to be adjusted (or we should just re-generate the cache in the container).

**Comment by Kevin-TD** [comment]
Is this issue still relevant? If not, we should close it

**Comment by kelloggm** [comment]
I don't think so.
