### ISSUE TITLE
Command in README isn't correct

### ISSUE THREAD

**Issue by kelloggm** [Kevin-TD/c-resource-leak-checker#3]
The following command (step 8 in the README) leads to an error:
> opt -load MustCallPass.so -MustCallPass ../test/test2.ll

The error is:
> opt: Unknown command line argument '-MustCallPass'.  Try: 'opt -help'
> opt: Did you mean '-MustCallEstimates'?

Changing `-MustCallPass` to `-MustCallEstimates` in the command gives output.

**Comment by Kevin-TD** [comment]
Did you clone the main branch or the must-call-development branch? Running the readme commands on the main branch I come across the opt error but it's not the case for the other branch. 
If you ran the main branch, then apologies; should've mentioned somewhere that you should've cloned the must-call-development branch. The main branch is quite behind the must-call-development branch

**Comment by kelloggm** [comment]
> Did you clone the main branch or the must-call-development branch? Running the readme commands on the main branch I come across the opt error but it's not the case for the other branch.

I was in fact running on the `main` branch. I'll give it another try using the `called-methods-development` branch as soon as I get a chance.
